import { Banner } from "./types"

export const MOCK_BANNERS: Banner[] = [
  {
    id: 1,
    title: "Biblioteca Digital Colaborativa",
    description: "Acesse milhares de livros acadêmicos, TCCs e artigos científicos. Faça anotações e compartilhe conhecimento.",
    type: "library",
    link: "/library",
    bgColor: "bg-gradient-to-r from-indigo-600 to-purple-600",
    textColor: "text-white",
    buttonText: "Explorar Biblioteca",
  },
  {
    id: 2,
    title: "Fórum: Inteligência Artificial e Ética",
    description: "Debate atual sobre os impactos da IA na sociedade. Participe com especialistas da área.",
    type: "forum",
    date: "Debate ao vivo: 15/03/2024",
    link: "/forums/ai-ethics",
    bgColor: "bg-gradient-to-r from-blue-600 to-cyan-600",
    textColor: "text-white",
    buttonText: "Participar",
  },
  {
    id: 3,
    title: "Programa de Mentoria Acadêmica",
    description: "Conecte-se com pesquisadores experientes e receba orientação para seus estudos.",
    type: "partnership",
    link: "/mentorship",
    bgColor: "bg-gradient-to-r from-emerald-600 to-teal-600",
    textColor: "text-white",
    buttonText: "Inscrever-se",
  },
  {
    id: 4,
    title: "Estudo Colaborativo: Mudanças Climáticas",
    description: "Projeto interdisciplinar com participação de Harvard, USP e MIT",
    type: "study",
    date: "Inscrições até 31/03/2024",
    link: "/studies/climate-change",
    bgColor: "bg-gradient-to-r from-green-600 to-emerald-600",
    textColor: "text-white",
    institution: "Harvard, USP, MIT",
    buttonText: "Contribuir",
  },
  {
    id: 5,
    title: "Prêmio Brio de Inovação Acadêmica",
    description: "Reconhecimento para as melhores contribuições científicas da plataforma",
    type: "award",
    date: "Inscrições até 30/04/2024",
    link: "/awards/innovation",
    bgColor: "bg-gradient-to-r from-amber-500 to-orange-600",
    textColor: "text-white",
    buttonText: "Candidate-se",
  },
  {
    id: 6,
    title: "Curso: Deep Learning Aplicado",
    description: "Aprenda técnicas avançadas de Deep Learning com professores do MIT e Stanford",
    type: "course",
    date: "Início: 01/05/2024",
    link: "/courses/deep-learning",
    bgColor: "bg-gradient-to-r from-violet-600 to-purple-600",
    textColor: "text-white",
    institution: "MIT, Stanford",
    buttonText: "Matricular-se",
  },
  {
    id: 7,
    title: "Evento: Simpósio Internacional de Neurociência",
    description: "Três dias de palestras, workshops e networking com pesquisadores de todo o mundo",
    type: "event",
    date: "20-22/06/2024",
    link: "/events/neuroscience-symposium",
    bgColor: "bg-gradient-to-r from-rose-600 to-pink-600",
    textColor: "text-white",
    institution: "Oxford, Cambridge, USP",
    buttonText: "Inscrever-se",
  },
  {
    id: 8,
    title: "Promoção: Acesso Premium",
    description: "50% de desconto no plano anual. Acesse todos os recursos premium da plataforma",
    type: "promotion",
    date: "Válido até 30/03/2024",
    link: "/premium/promo",
    bgColor: "bg-gradient-to-r from-yellow-500 to-orange-500",
    textColor: "text-white",
    buttonText: "Aproveitar",
  }
] 